### ISSUE TITLE
UI Protototyping

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-timeline#2]
Series of versions with increasing functionality:
* [x] Hello world in a branch titled `UI_Prototyping`, in a Draft Pull Request. The first line of the description should include `Fixes #2` - to link it to this issue.
* [x] Ian will configure repo to deploy PRs to Heroku
* [x] Add timeline [example](https://github.com/flrs/visavail#1-description)

Further steps to work towards the mockup provided [here](https://pepys-import.slack.com/archives/C01DH167KV1/p1618049389000800):
* [x] Build timeline from JSON formatted similar to [expected](https://github.com/debrief/pepys-import/issues/840#issuecomment-816179135) SQL results
* [ ] In use, data will be loaded during the day, and the timelines will _fill-up_ as more data is loaded.  We can simulate this by letting the user switch between JSON data sources.  Add a `Data Received` button to switch that switches the view to a different JSON mock data source (that contains increased coverage)
* [x] In addition to the time coverage, the timeline will show that some ships only participated for part of the exercise.  This is represented by a light-grey bar, shown behind the coloured coverage bars. Add participation time (light grey bar) for some platforms, that shows they weren't present for whole trial
* [ ] Build flask (or Panel) app with REST API that loads front-end, and returns JSON data. YAML config file will provide database connection parameters & update frequency. YAML file not pushed to GitHub
* [ ] Configure Heroku [hosting](https://devcenter.heroku.com/categories/python-support) for Python app. Ian should invite @robintw to setup/configure this
* [ ] Provide database connection parameters as Heroku 
* [ ] Connect app to PostGres

Note: where possible we should try to keep the chart rendering code isolated as a component - to ease the possibility of it becoming a SuperSet plugin in the future.

**Comment by krsnik93** [comment]
Live instance at ec2-34-219-150-21.us-west-2.compute.amazonaws.com can be used to check progress.

**Comment by IanMayo** [comment]
Hello @krsnik93 - I guess that if you're available for work, but held back by lack of test data you could pick off some other steps above, and not necessarily do them in a linear fashion.

**Comment by krsnik93** [comment]
I am having trouble understanding these completely:

> Add button to switch to new JSON object (that contains increased coverage)
Add icons for platform-type (I can provide SVG icons from here)
Add participation time (light grey bar) for some platform, that shows they weren't present for whole trial
Add %age coverage for platform (vehicle)

Should I start on this one and create a skeleton:
> Build flask (or Panel) app with REST API that loads front-end, and returns JSON data. YAML config file will provide database connection parameters & update frequency. YAML file not pushed to GitHub

**Comment by IanMayo** [comment]
> create a skeleton

sure, yes. Good plan.

I'll make a note to expand the other notes tomorrow.

**Comment by IanMayo** [comment]
Hello @krsnik93  - I've expanded the detail on those earlier steps. Hopefully they make more sense now.

**Comment by IanMayo** [comment]
Aah, another thing @krsnik93 .  Now that we have the Python middleware - we can let Python do some transformation of the data before it gets rendered.

That means it is worth progressing with the display of some dummy data - so you can decide what format you require Python to provide it in.

Here is a sample dataset to get you started:
* Serial: `J05130 - CASEX 324`
* Start time: 1000
* End time: 1200
* Participant 1:
    * Name: `RICH`
    * Coverage: 1000-1040, 1050-1105, 1130-1200
* Participant 2:
    * Name: `DUKE`
    * Coverage: 1015-1030, 1035-1100, 1140-1200
* Participant 3:
    * Name: `CUMB`
    * Coverage: 1000-1005, 1045-1100, 1145-1200

**Comment by krsnik93** [comment]
Would you prefer a plot like this:
![image](https://user-images.githubusercontent.com/13034472/114604570-ef5ceb80-9c90-11eb-9f68-087ef929f200.png)
or do you want the missing periods to be marked with a color as well? Visavail has red as the default one, but I seem to remember light gray being mentioned somewhere in `pepys-import`?

Basically if we wanted to mark the missing periods as well, we would have to construct the periods for those times as well. Bad API by visavail, but managable if necessary. 

What I mean is that Visavail expects the user to input the missing periods as well, something like this:
```
"data":  [
  ["2016-01-01 12:00:00", 1, "2016-01-01 13:00:00"],
  ["2016-01-01 14:22:51", 1, "2016-01-01 16:14:12"],
  ["2016-01-01 19:20:05", 0, "2016-01-01 20:30:00"],
  ["2016-01-01 20:30:00", 1, "2016-01-01 22:00:00"]
]
```
The second value in each row denotes observed/missing. So we would have to fill in the blanks between the observed periods.

I can do it either way, let me know.

EDIT: Just a reminder how it looks like with red:
![image](https://user-images.githubusercontent.com/13034472/114605126-a6f1fd80-9c91-11eb-9bca-e9bc70b48e10.png)

**Comment by krsnik93** [comment]
Update, I figured out a very simple way to mark "everything else" as missing:
![image](https://user-images.githubusercontent.com/13034472/114606081-bc1b5c00-9c92-11eb-9014-c8e05f3f003e.png)

I believe it's trivial to change the red to something a bit less pronounced.

**Comment by IanMayo** [comment]
Nice work!

**Comment by krsnik93** [comment]
I was not able to prepend icons to participant names. Visavail uses svg to display these elements. I will revisit later.

**Comment by IanMayo** [comment]
@krsnik93  - the "some ships only participatd for part of an exercise" relates to this instance:
![image](https://user-images.githubusercontent.com/1108513/114828161-7b6e3080-9dc1-11eb-9ef1-df5e9ef40d08.png)

In that example was only expected to take part for the first 4/5 of the exercise.  So, the analysts don't need to wait until the bar is fully green - they only need it to be green for the first 4/5.

This effectively gives us 3 states:
- data present (green)
- data not present for period when ship taking part (grey)
- data not present for period when ship not taking part (white)

I appreciate that `visavail` may not be able to handle that - so we may have to do some pre-processing in Python.

**Comment by krsnik93** [comment]
Visavail actually has this but we would have to explicitly pass grey periods as well. So not only green ones but grey as well.

**Comment by IanMayo** [comment]
Issue description modified to remove visual elements that have been moved to #4 

@krsnik93 - while I provided the times as `1000-1200` they will actually be provided in ISO format.  So, if you change your data to ISO format a few 10s of lines can be removed.  Hold on - I'll have a go at that myself. I'll also try to insert some more metadata that will be useful for #4

**Comment by IanMayo** [comment]
Ok.  I merged the original #3 prototyping branch.

I propose that the remaining tasks in this issue be resolved in a new`feature/2_backend` branch & tracking PR.

**Comment by IanMayo** [comment]
Closing this issue. We'll cover the remaining tasks/features as separate issues. Flask work moved here #5
